name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à 00:00 UTC (ajuste se quiser)
  workflow_dispatch:      # permite rodar manualmente
  push:
    branches:
      - main

permissions:
  contents: write        # permite ao workflow escrever/empurrar arquivos

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Pac-Man contribution graph
        # action oficial do projeto Pac-Man (gera SVG(s) em ./dist)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy generated SVGs to output branch
        # publica tudo que estiver em ./dist para o branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
